# Importing Libraries

In [1]:
from keras.models import Sequential 

In [2]:
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization 

In [3]:
from keras.layers import Activation, Dropout, Flatten, Dense

In [4]:
import os
import cv2
from PIL import Image
import numpy as np


# Data Collection

In [5]:
import cv2

classes = {'fresh_capsicum':0,'stale_capsicum':1}
x=[]
y=[]
for cls in classes:
    pth='C:\\vege\\'+cls
    for j in os.listdir(pth):
        img=cv2.imread(os.path.join(pth,j),0)
        img=cv2.resize(img,(200,200))
        x.append(img)
        y.append(classes[cls])

In [6]:
print(classes)

{'fresh_capsicum': 0, 'stale_capsicum': 1}


In [7]:
y = np.array(y)
x = np.array(x)

In [8]:
print(x[10])

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [231 234 232 ...   0   0   0]
 [230 231 231 ...   0   0   0]
 [228 229 231 ...   0   0   0]]


# Data Splitting 

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0, stratify = y)



# Data Normalization 

In [10]:

X_train = X_train / 255.0
X_test = X_test / 255.0


# Building Neural Networks

In [11]:
INPUT_SHAPE = (200, 200, 1)   #change to (SIZE, SIZE, 3)


model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape=INPUT_SHAPE))
          
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(32, (3, 3), kernel_initializer = 'he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3), kernel_initializer = 'he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(1))
model.add(Activation('sigmoid'))  

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',             #also try adam
              metrics=['accuracy'])

In [12]:
print(model.summary())    

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 198, 198, 32)      320       
                                                                 
 activation (Activation)     (None, 198, 198, 32)      0         
                                                                 
 max_pooling2d (MaxPooling2  (None, 99, 99, 32)        0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 97, 97, 32)        9248      
                                                                 
 activation_1 (Activation)   (None, 97, 97, 32)        0         
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 48, 48, 32)        0         
 g2D)                                                   

# Model training

In [13]:
model.fit(X_train, y_train, epochs=30, batch_size=32, validation_split=0.2)


Epoch 1/30


38/38 [==============================] - 12s 287ms/step - loss: 0.8557 - accuracy: 0.5335 - val_loss: 0.6588 - val_accuracy: 0.7228
Epoch 2/30
38/38 [==============================] - 10s 275ms/step - loss: 0.6472 - accuracy: 0.6212 - val_loss: 0.5633 - val_accuracy: 0.7327
Epoch 3/30
38/38 [==============================] - 10s 271ms/step - loss: 0.5673 - accuracy: 0.7113 - val_loss: 0.8561 - val_accuracy: 0.5479
Epoch 4/30
38/38 [==============================] - 10s 264ms/step - loss: 0.5169 - accuracy: 0.7502 - val_loss: 0.4599 - val_accuracy: 0.7789
Epoch 5/30
38/38 [==============================] - 10s 264ms/step - loss: 0.4783 - accuracy: 0.7792 - val_loss: 0.4577 - val_accuracy: 0.7888
Epoch 6/30
38/38 [==============================] - 10s 264ms/step - loss: 0.4017 - accuracy: 0.8263 - val_loss: 0.4125 - val_accuracy: 0.8119
Epoch 7/30
38/38 [==============================] - 10s 256ms/step - loss: 0.4017 - accuracy: 0.8197 - val_loss: 0.3858 - val_accuracy: 0.79

# Prediction


In [14]:
import os
os.getcwd()

'C:\\Users\\ACER\\Desktop\\New_proj'

In [21]:
import cv2
image_p= "stale.JPG"
image=cv2.imread(image_p)
image = cv2.resize(image,(200,200))
image = image.reshape(3,200,200,1) / 255.0
q=model.predict(image)
print(q)
if(q[0]>0.5):
    print("Poor Quality")
else:
    print("Good Quality")
    


1/1 [==============================] - 0s 27ms/step
[[1.       ]
 [1.       ]
 [0.9999277]]
Poor Quality
